### ISSUE TITLE
rendering a  colored body mesh

### ISSUE THREAD

**Issue by athena913** [sergeyprokudin/smplpix#26]
Hi,  
Thank you for the great work and making the code available.

I was able to run smplify-x and get a non-colored mesh output with visualize=False. If I set visualize=True, then pyrender fails to produce an output (just hangs). I tried out the suggestions in the pyrender docs for offscreen rendering using osmesa, but that did not help either. I suspect it is because pyrender requires python 3.8, but I am using python 3.7 since I had issues  installing smplify-x  dependencies  on python 3.8. 
- Is there an alternative to pyrender that I can use to generate the colored rendering of the body mesh during training, which I can then use as input to smplpix?  
- If not, is there a way to get the required colored rendering after the mesh has been generated by smplify-x?

thanks

**Comment by felixshing** [comment]
Hello, did you solve this problem? On my side, even though I make visualize=True, the output is still not the colored mesh, instead, it shows how the model fits the 3D model and outputs an image showing the 3D mesh overlapping with the original image. Anyway, I just cannot get the colored mesh, which is the input of this work.

**Comment by sergeyprokudin** [comment]
Hi @felixshing!

A good alternative to PyRender is [Pytorch3D](https://pytorch3d.org/), but you will need to figure out the conversion of camera parameters.

As an alternative solution, you can simply render the meshes produced by SMPLify-X with a separate run of pyrender with a correct Python version (if that is indeed the problem).

~Sergey

**Comment by felixshing** [comment]
Hi @sergeyprokudin Thank you so much for your reply. Actually, my question was originated from the color of your generated colored SMPLX mesh, as shown below. For example, the leg is in purple and arm is in green. However, my mesh generated from SMPLify-X does not contain such color. I thought your version of SMPLify-X could learn some color information from the input. But later on, after investigation, I found that this is because you use a generic color file for SMPLX named "smplx_verts_colors.txt" and you made some changes to render mesh, in order to let rendered mesh has colors: https://github.com/sergeyprokudin/smplify-x/blob/74e112507b07c821d55411db916c5a6fc6cf45e5/smplifyx/fit_single_frame.py#L565 

I would like to ask where this color file comes from and what is the function of this color information on SMPLX?

![image](https://github.com/sergeyprokudin/smplpix/assets/61814345/02f8ab71-0b8e-4d9d-ab48-2c3333c51e58)

**Comment by erotavlas** [comment]
> Hi @athena913, @felixshing !
> 
> A good alternative to PyRender is [Pytorch3D](https://pytorch3d.org/), but you will need to figure out the conversion of camera parameters.
> 
> As an alternative solution, you can simply render the meshes produced by SMPLify-X with a separate run of pyrender with a correct Python version (if that is indeed the problem).
> 
> ~Sergey

Just curious, how did you get this notebook to work if torch 1.1.0 max python version is 3.7 yet in the code is importing pyrender which required python 3.8?  

Can you show an example how to run render on it's own in the command line with arguments? 

EDIT: While I was typing this I tried upgrading my env to python 3.8, reinstalled torch 1.14.0, pillow, scipy, and numpy, then fixed this error https://stackoverflow.com/questions/65637222/runtimeerror-subtraction-the-operator-with-a-bool-tensor-is-not-supported by modifying the conversions.py file in torchgeometry folder.  And everythign seems to work and I get the render with the rest of the output.
